### PR TITLE
Add java block placeholders for all files

### PR DESCRIPTION
**Pull request by ArchdukeTim**

### CODE REVIEW

**Comment by Daniel1464** [comment]
This is probably going to be extremely tedious, but I think we should maybe add a disclaimer that these sections are TBD, unless if we aren't going to ship these soon

**Review by falOn-Dev — APPROVED** [review]

**Comment by ArchdukeTim** [comment]
@Daniel1464 maybe we can add in a bit to the plugin code that inserts a disclaimer until the version is marked as good to go or something. Or we can utilize the .gittrack files and header and only include files that have been verified

**Comment by Daniel1464** [comment]
Alright I added a disclaimer for stuff

Btw tim, could you tell me how u propose direct edits to a PR? I am trying to figure that out and can't seem to do so

**Review by Daniel1464 — APPROVED** [review]

**Comment by ArchdukeTim** [comment]
@Daniel1464 I updated the notice to use the source track validation line instead of requiring us to put a new line in the other file. Should be cleaner. It also just won't generate the kotlin block, instead of showing java with a notice. I think that's better since it'll be a better UX.

Thoughts?

**Comment by Daniel1464** [comment]
Yeah that's probably better tbh; my solution probably wasn't the best in hindsight but yeah

**Pull request merged**
